#ifndef __UNSAFE_MATH_MACROS__
#define __UNSAFE_MATH_MACROS__

#define UNSAFE_unary_minus(X) (-(X))
#define UNSAFE_add(X, Y) ((X)+(Y))
#define UNSAFE_sub(X, Y) ((X)-(Y))
#define UNSAFE_mul(X, Y) ((X)*(Y))
#define UNSAFE_mod(X, Y) ((X)%(Y))
#define UNSAFE_div(X, Y) ((X)/(Y))
#define UNSAFE_lshift(X, Y) ((X)<<(Y))
#define UNSAFE_rshift(X, Y) ((X)>>(Y))

#define UNSAFE_unary_minus_func_int8_t_s(_si) UNSAFE_unary_minus(_si)
#define UNSAFE_add_func_int8_t_s_s(_si1,_si2) UNSAFE_add(_si1,_si2)
#define UNSAFE_sub_func_int8_t_s_s(_si1,_si2) UNSAFE_sub(_si1,_si2)
#define UNSAFE_mul_func_int8_t_s_s(_si1,_si2) UNSAFE_mul(_si1,_si2)
#define UNSAFE_mod_func_int8_t_s_s(_si1,_si2) UNSAFE_mod(_si1,_si2)
#define UNSAFE_div_func_int8_t_s_s(_si1,_si2) UNSAFE_div(_si1,_si2)
#define UNSAFE_lshift_func_int8_t_s_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_int8_t_s_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_int8_t_s_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_int8_t_s_u(_left,_right) UNSAFE_rshift(_left,_right)

#define UNSAFE_unary_minus_func_int16_t_s(_si) UNSAFE_unary_minus(_si)
#define UNSAFE_add_func_int16_t_s_s(_si1,_si2) UNSAFE_add(_si1,_si2)
#define UNSAFE_sub_func_int16_t_s_s(_si1,_si2) UNSAFE_sub(_si1,_si2)
#define UNSAFE_mul_func_int16_t_s_s(_si1,_si2) UNSAFE_mul(_si1,_si2)
#define UNSAFE_mod_func_int16_t_s_s(_si1,_si2) UNSAFE_mod(_si1,_si2)
#define UNSAFE_div_func_int16_t_s_s(_si1,_si2) UNSAFE_div(_si1,_si2)
#define UNSAFE_lshift_func_int16_t_s_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_int16_t_s_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_int16_t_s_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_int16_t_s_u(_left,_right) UNSAFE_rshift(_left,_right)

#define UNSAFE_unary_minus_func_int32_t_s(_si) UNSAFE_unary_minus(_si)
#define UNSAFE_add_func_int32_t_s_s(_si1,_si2) UNSAFE_add(_si1,_si2)
#define UNSAFE_sub_func_int32_t_s_s(_si1,_si2) UNSAFE_sub(_si1,_si2)
#define UNSAFE_mul_func_int32_t_s_s(_si1,_si2) UNSAFE_mul(_si1,_si2)
#define UNSAFE_mod_func_int32_t_s_s(_si1,_si2) UNSAFE_mod(_si1,_si2)
#define UNSAFE_div_func_int32_t_s_s(_si1,_si2) UNSAFE_div(_si1,_si2)
#define UNSAFE_lshift_func_int32_t_s_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_int32_t_s_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_int32_t_s_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_int32_t_s_u(_left,_right) UNSAFE_rshift(_left,_right)

#define UNSAFE_unary_minus_func_int64_t_s(_si) UNSAFE_unary_minus(_si)
#define UNSAFE_add_func_int64_t_s_s(_si1,_si2) UNSAFE_add(_si1,_si2)
#define UNSAFE_sub_func_int64_t_s_s(_si1,_si2) UNSAFE_sub(_si1,_si2)
#define UNSAFE_mul_func_int64_t_s_s(_si1,_si2) UNSAFE_mul(_si1,_si2)
#define UNSAFE_mod_func_int64_t_s_s(_si1,_si2) UNSAFE_mod(_si1,_si2)
#define UNSAFE_div_func_int64_t_s_s(_si1,_si2) UNSAFE_div(_si1,_si2)
#define UNSAFE_lshift_func_int64_t_s_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_int64_t_s_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_int64_t_s_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_int64_t_s_u(_left,_right) UNSAFE_rshift(_left,_right)

#define UNSAFE_unary_minus_func_uint8_t_u(_ui) UNSAFE_unary_minus(_ui)
#define UNSAFE_add_func_uint8_t_u_u(_ui1,_ui2) UNSAFE_add(_ui1,_ui2)
#define UNSAFE_sub_func_uint8_t_u_u(_ui1,_ui2) UNSAFE_sub(_ui1,_ui2)
#define UNSAFE_mul_func_uint8_t_u_u(_ui1,_ui2) UNSAFE_mul(_ui1,_ui2)
#define UNSAFE_mod_func_uint8_t_u_u(_ui1,_ui2) UNSAFE_mod(_ui1,_ui2)
#define UNSAFE_div_func_uint8_t_u_u(_ui1,_ui2) UNSAFE_div(_ui1,_ui2)
#define UNSAFE_lshift_func_uint8_t_u_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_uint8_t_u_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_uint8_t_u_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_uint8_t_u_u(_left,_right) UNSAFE_rshift(_left,_right)

#define UNSAFE_unary_minus_func_uint16_t_u(_ui) UNSAFE_unary_minus(_ui)
#define UNSAFE_add_func_uint16_t_u_u(_ui1,_ui2) UNSAFE_add(_ui1,_ui2)
#define UNSAFE_sub_func_uint16_t_u_u(_ui1,_ui2) UNSAFE_sub(_ui1,_ui2)
#define UNSAFE_mul_func_uint16_t_u_u(_ui1,_ui2) UNSAFE_mul(_ui1,_ui2)
#define UNSAFE_mod_func_uint16_t_u_u(_ui1,_ui2) UNSAFE_mod(_ui1,_ui2)
#define UNSAFE_div_func_uint16_t_u_u(_ui1,_ui2) UNSAFE_div(_ui1,_ui2)
#define UNSAFE_lshift_func_uint16_t_u_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_uint16_t_u_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_uint16_t_u_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_uint16_t_u_u(_left,_right) UNSAFE_rshift(_left,_right)

#define UNSAFE_unary_minus_func_uint32_t_u(_ui) UNSAFE_unary_minus(_ui)
#define UNSAFE_add_func_uint32_t_u_u(_ui1,_ui2) UNSAFE_add(_ui1,_ui2)
#define UNSAFE_sub_func_uint32_t_u_u(_ui1,_ui2) UNSAFE_sub(_ui1,_ui2)
#define UNSAFE_mul_func_uint32_t_u_u(_ui1,_ui2) UNSAFE_mul(_ui1,_ui2)
#define UNSAFE_mod_func_uint32_t_u_u(_ui1,_ui2) UNSAFE_mod(_ui1,_ui2)
#define UNSAFE_div_func_uint32_t_u_u(_ui1,_ui2) UNSAFE_div(_ui1,_ui2)
#define UNSAFE_lshift_func_uint32_t_u_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_uint32_t_u_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_uint32_t_u_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_uint32_t_u_u(_left,_right) UNSAFE_rshift(_left,_right)

#define UNSAFE_unary_minus_func_uint64_t_u(_ui) UNSAFE_unary_minus(_ui)
#define UNSAFE_add_func_uint64_t_u_u(_ui1,_ui2) UNSAFE_add(_ui1,_ui2)
#define UNSAFE_sub_func_uint64_t_u_u(_ui1,_ui2) UNSAFE_sub(_ui1,_ui2)
#define UNSAFE_mul_func_uint64_t_u_u(_ui1,_ui2) UNSAFE_mul(_ui1,_ui2)
#define UNSAFE_mod_func_uint64_t_u_u(_ui1,_ui2) UNSAFE_mod(_ui1,_ui2)
#define UNSAFE_div_func_uint64_t_u_u(_ui1,_ui2) UNSAFE_div(_ui1,_ui2)
#define UNSAFE_lshift_func_uint64_t_u_s(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_lshift_func_uint64_t_u_u(_left,_right) UNSAFE_lshift(_left,_right)
#define UNSAFE_rshift_func_uint64_t_u_s(_left,_right) UNSAFE_rshift(_left,_right)
#define UNSAFE_rshift_func_uint64_t_u_u(_left,_right) UNSAFE_rshift(_left,_right)

#endif
